# Generated by Django 2.2.1 on 2019-05-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numControl', models.IntegerField(verbose_name='numero de control')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='promedio')),
                ('semestre', models.IntegerField(verbose_name='semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='carrera')),
                ('especialidad', models.CharField(max_length=50, verbose_name='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituto', models.CharField(max_length=50, verbose_name='instituto')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50, verbose_name='materia')),
                ('creditos', models.IntegerField(verbose_name='creditos')),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Carrera', verbose_name='id carrera')),
                ('idInstituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Instituto', verbose_name='id instituto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='plan')),
                ('semVal', models.IntegerField(verbose_name='semestres de validacion')),
                ('coment', models.CharField(max_length=320, verbose_name='comentarios')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('coment', models.CharField(max_length=320, verbose_name='comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='tipo de status')),
                ('descStat', models.CharField(max_length=50, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, verbose_name='user')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('tipoUsuario', models.IntegerField(verbose_name='tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSolic', models.DateField(auto_now=True, verbose_name='fecha de registro')),
                ('coment', models.CharField(max_length=320, verbose_name='comentario')),
                ('idAcademia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Academia', verbose_name='id academia')),
                ('idInstituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Instituto', verbose_name='instituto')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.ServicioEscolar', verbose_name='id servicio escolar')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Status', verbose_name='status')),
                ('numeroControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Alumno', verbose_name='numero de control')),
            ],
        ),
        migrations.AddField(
            model_name='servicioescolar',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Usuario', verbose_name=''),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50, verbose_name='municipio')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Estado', verbose_name='id estado')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='fecha de movimiento')),
                ('idSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Solicitud', verbose_name='id solicitud')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Status', verbose_name='id status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Usuario', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaSolicitada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calif', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='calificacion')),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Carrera', verbose_name='')),
                ('idInstituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Instituto', verbose_name='id instituto')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Materia', verbose_name='id materia')),
                ('idSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Solicitud', verbose_name='id solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='MateriasDelAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calif', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='calificacion')),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Carrera', verbose_name='carrera')),
                ('idInstituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Instituto', verbose_name='instituto')),
                ('idMaterias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Materia', verbose_name='materia')),
                ('numControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Alumno', verbose_name='numero de control')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=50, verbose_name='localidad')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Municipio', verbose_name='id municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Jefatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Usuario', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='instituto',
            name='idLocalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Localidad', verbose_name='id localidad'),
        ),
        migrations.AddField(
            model_name='estado',
            name='idPais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Pais', verbose_name='id pais'),
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Carrera', verbose_name='')),
                ('idJefatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Jefatura', verbose_name='id jefatura')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Usuario', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='idInstituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Instituto', verbose_name='id instituto'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Carrera', verbose_name='carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Usuario', verbose_name='nombre de usuario'),
        ),
        migrations.AddField(
            model_name='academia',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simel.Usuario', verbose_name=''),
        ),
    ]
