# Generated by Django 2.2.1 on 2019-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='tipoStatus',
            field=models.IntegerField(default=1, verbose_name='tipo de status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='descStat',
            field=models.CharField(max_length=50, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50, verbose_name='status'),
        ),
    ]
