# Generated by Django 2.2.1 on 2019-05-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='idCarrera',
        ),
    ]
