# Generated by Django 2.2.1 on 2019-05-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simel', '0002_remove_solicitud_idcarrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='horaSolic',
            field=models.TimeField(auto_now=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='coment',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='comentario'),
        ),
    ]
