# Generated by Django 2.2.1 on 2019-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simel', '0003_aduedo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduedo',
            name='eligible',
            field=models.BooleanField(default=True, verbose_name='Es eligible'),
        ),
        migrations.AddField(
            model_name='aduedo',
            name='matRC',
            field=models.IntegerField(default=0, verbose_name='materias cursadando en RC'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='es usaurio activo'),
        ),
    ]
